# Site settings
title: DondreKhan's blog
email: dondrekhan@akula.sturmkrieg.ru
description: "Thoughts on a chaotic world"
baseurl: ""
url: "http://aleksandra.meinho.lt"

# Build settings
markdown: kramdown
permalink: pretty
